<?php

/**
 * Centralized Job Positions Configuration
 * Used across Hiring Leads, Employees, and other HR modules
 */

return [
    'groups' => [
        'Development' => [
            'Full Stack Developer',
            'Frontend Developer',
            'Backend Developer',
            'Mobile App Developer',
            'DevOps Engineer',
            'Quality Assurance Engineer',
            'Software Engineer',
            'Junior Developer',
            'Senior Developer',
        ],
        'Design' => [
            'UI/UX Designer',
            'Graphic Designer',
            'Web Designer',
            'Motion Graphics Designer',
        ],
        'Management' => [
            'Project Manager',
            'Team Lead',
            'Operations Manager',
            'General Manager',
            'CEO',
            'CTO',
            'COO',
        ],
        'Human Resources' => [
            'HR Executive',
            'HR Manager',
            'Recruiter',
            'HR Intern',
        ],
        'Sales & Marketing' => [
            'Sales Executive',
            'Sales Manager',
            'Marketing Executive',
            'Digital Marketing Specialist',
            'Content Writer',
            'SEO Specialist',
            'Social Media Manager',
            'Business Development Executive',
            'Business Development Manager',
        ],
        'Finance & Accounting' => [
            'Accountant',
            'Finance Manager',
            'Accounts Executive',
            'Tax Consultant',
        ],
        'Support & Administration' => [
            'Customer Support Executive',
            'Technical Support Engineer',
            'Receptionist',
            'Office Administrator',
            'Data Entry Operator',
        ],
        'Other Roles' => [
            'Business Analyst',
            'System Administrator',
            'Network Administrator',
            'Intern',
            'Trainee',
            'Other',
        ],
    ],

    // Flat list of all positions (for simple dropdowns)
    'all' => [
        'Full Stack Developer',
        'Frontend Developer',
        'Backend Developer',
        'Mobile App Developer',
        'DevOps Engineer',
        'Quality Assurance Engineer',
        'Software Engineer',
        'Junior Developer',
        'Senior Developer',
        'UI/UX Designer',
        'Graphic Designer',
        'Web Designer',
        'Motion Graphics Designer',
        'Project Manager',
        'Team Lead',
        'Operations Manager',
        'General Manager',
        'CEO',
        'CTO',
        'COO',
        'HR Executive',
        'HR Manager',
        'Recruiter',
        'HR Intern',
        'Sales Executive',
        'Sales Manager',
        'Marketing Executive',
        'Digital Marketing Specialist',
        'Content Writer',
        'SEO Specialist',
        'Social Media Manager',
        'Business Development Executive',
        'Business Development Manager',
        'Accountant',
        'Finance Manager',
        'Accounts Executive',
        'Tax Consultant',
        'Customer Support Executive',
        'Technical Support Engineer',
        'Receptionist',
        'Office Administrator',
        'Data Entry Operator',
        'Business Analyst',
        'System Administrator',
        'Network Administrator',
        'Intern',
        'Trainee',
        'Other',
    ],
];
